name: shinyapps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Main
      run: |
           docker pull rocker/shiny-verse:3.6.3
